const owners = {
  Eudes: {
    name: 'Eudes Araújo',
    role: 'Sites, SEO, criação de marca e branding',
    photo: 'assets/equipe/eudes-araujo.png',
    photoAlt: 'Eudes Araújo, responsável por sites, SEO, criação de marca e branding na Oriz',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  Wallyson: {
    name: 'Wallyson Dias',
    role: 'Tráfego, estratégia de marketing e visão de negócios',
    photo: 'assets/equipe/wallyson-dias.png',
    photoAlt: 'Wallyson Dias, responsável por tráfego e estratégia de marketing na Oriz',
    bio: 'Wallyson Dias conduz as frentes de tráfego e estratégia da Oriz. Graduando em Direito, desenvolve um olhar especialmente atento ao mercado jurídico e ao contexto empresarial, conectando comunicação, aquisição e visão de negócio para identificar soluções que vão além da presença digital.',
  },
}

const services = [
  {
    slug: 'trafego-pago',
    name: 'Tráfego pago',
    owner: 'Wallyson',
    eyebrow: 'MÍDIA COM DIREÇÃO',
    promise: 'Campanhas que partem do negócio, não do botão impulsionar.',
    context: 'Tráfego pago faz sentido quando existe uma oferta clara, um objetivo comercial e disposição para aprender com os dados. A Oriz organiza esses elementos para transformar investimento em uma operação de aquisição mais consciente.',
    deliverables: ['Planejamento de mídia e públicos', 'Estrutura de campanhas em Google e Meta', 'Tracking e leitura de conversões', 'Rotina de análise e otimização'],
    process: [['Diagnóstico', 'Entendemos oferta, público, margem e momento do negócio.'], ['Estrutura', 'Definimos canais, mensagens, eventos e prioridades de teste.'], ['Distribuição', 'Colocamos as campanhas no ar com controle e leitura desde o início.'], ['Otimização', 'Ajustamos investimento e comunicação a partir de sinais reais.']],
    faqs: [['Qual é o investimento mínimo?', 'O valor depende do mercado, da oferta e do objetivo. A recomendação nasce do diagnóstico, sem uma verba universal inventada.'], ['A Oriz cria os anúncios?', 'Planejamos a direção das peças e conectamos criação, página e mídia para que a campanha funcione como sistema.'], ['Quando os resultados aparecem?', 'Campanhas começam a gerar dados desde o lançamento, mas decisões consistentes exigem volume, contexto e ciclos de aprendizagem.']],
    related: ['estrategia-de-marketing', 'criacao-de-sites', 'seo'],
  },
  {
    slug: 'estrategia-de-marketing',
    name: 'Estratégia de marketing',
    owner: 'Wallyson',
    eyebrow: 'CLAREZA ANTES DA EXECUÇÃO',
    promise: 'Uma direção comum para mensagem, canais e crescimento.',
    context: 'Quando iniciativas isoladas competem entre si, o marketing perde força. A estratégia organiza prioridades, define o papel de cada canal e cria critérios para decidir o que fazer agora, depois e por quê.',
    deliverables: ['Diagnóstico de cenário e presença', 'Objetivos, públicos e proposta de valor', 'Plano de canais e conteúdo', 'Ritmo de execução e indicadores'],
    process: [['Imersão', 'Reunimos contexto do negócio, mercado e desafios atuais.'], ['Escolhas', 'Transformamos possibilidades em prioridades claras.'], ['Plano', 'Conectamos mensagem, canais, responsabilidades e cadência.'], ['Aprendizado', 'Revisitamos decisões com base no que a execução revela.']],
    faqs: [['A estratégia inclui execução?', 'A página trata da direção estratégica; o escopo pode conectar serviços de mídia, marca, site e SEO conforme a necessidade.'], ['Serve para empresas pequenas?', 'Serve para negócios que precisam fazer escolhas melhores com o tempo, equipe e orçamento disponíveis.'], ['O plano fica engessado?', 'Não. Ele cria direção e critérios, mas evolui com mercado, dados e novas prioridades.']],
    related: ['trafego-pago', 'branding', 'seo'],
  },
  {
    slug: 'criacao-de-sites',
    name: 'Criação de sites',
    owner: 'Eudes',
    eyebrow: 'EXPERIÊNCIA DIGITAL',
    promise: 'Sites com clareza, presença e uma função real no negócio.',
    context: 'Um bom site não é apenas uma vitrine. Ele organiza a mensagem da marca, reduz dúvidas, sustenta campanhas e cria caminhos claros para a próxima ação do visitante.',
    deliverables: ['Arquitetura de informação e jornada', 'Direção visual responsiva', 'Desenvolvimento e microinterações', 'SEO técnico e medição essencial'],
    process: [['Descoberta', 'Definimos objetivo, público, conteúdo e requisitos.'], ['Arquitetura', 'Organizamos páginas e hierarquia antes de decorar a interface.'], ['Design e código', 'Construímos a experiência com atenção a ritmo e desempenho.'], ['Entrega', 'Validamos navegação, responsividade e base de mensuração.']],
    faqs: [['O site funciona no celular?', 'Sim. A experiência é pensada de forma responsiva desde a arquitetura até a verificação final.'], ['Vocês também escrevem os textos?', 'Podemos criar a copy institucional provisória e refiná-la com o repertório e as informações do negócio.'], ['O site já nasce preparado para SEO?', 'A estrutura técnica, semântica e de conteúdo é preparada desde o início; resultados orgânicos dependem também de continuidade.']],
    related: ['seo', 'criacao-de-marca', 'branding'],
  },
  {
    slug: 'seo',
    name: 'SEO',
    owner: 'Eudes',
    eyebrow: 'SER ENCONTRADO COM CONTEXTO',
    promise: 'Uma presença orgânica construída para pessoas e mecanismos de busca.',
    context: 'SEO conecta intenção de busca, conteúdo útil e uma base técnica legível. O trabalho da Oriz prioriza clareza e relevância para construir presença sem atalhos frágeis.',
    deliverables: ['Diagnóstico técnico e semântico', 'Arquitetura de temas e páginas', 'Otimização on-page', 'Plano de conteúdo e SEO local'],
    process: [['Leitura', 'Mapeamos o site, as buscas e os pontos de fricção.'], ['Arquitetura', 'Relacionamos temas, intenção e páginas com papéis definidos.'], ['Otimização', 'Melhoramos conteúdo, semântica e base técnica.'], ['Evolução', 'Acompanhamos sinais e ampliamos a cobertura com consistência.']],
    faqs: [['SEO garante primeira posição?', 'Não existe garantia legítima de posição. O trabalho cria condições técnicas e editoriais para competir com consistência.'], ['SEO substitui mídia paga?', 'Não. Os canais cumprem papéis diferentes e podem trabalhar juntos em uma estratégia de aquisição.'], ['SEO local serve para quem não tem loja?', 'Sim, desde que o conteúdo represente uma atuação regional real sem inventar endereço ou presença física.']],
    related: ['criacao-de-sites', 'estrategia-de-marketing', 'branding'],
  },
  {
    slug: 'criacao-de-marca',
    name: 'Criação de marca',
    owner: 'Eudes',
    eyebrow: 'IDENTIDADE COM SISTEMA',
    promise: 'Uma expressão reconhecível para a ideia que o negócio quer ocupar.',
    context: 'Criar uma marca é transformar estratégia em um sistema visual capaz de permanecer coerente em diferentes pontos de contato, do símbolo a uma página digital.',
    deliverables: ['Conceito e território visual', 'Logotipo e sistema de identidade', 'Paleta, tipografia e elementos gráficos', 'Aplicações essenciais e guia de uso'],
    process: [['Fundamento', 'Entendemos o negócio, o público e a diferença que precisa ganhar forma.'], ['Direções', 'Exploramos territórios visuais com intenção, não por tendência.'], ['Sistema', 'Desenvolvemos os elementos e suas relações.'], ['Aplicação', 'Testamos a identidade nos contextos em que ela precisa viver.']],
    faqs: [['Criação de marca é só um logotipo?', 'Não. O logotipo é uma peça de um sistema que inclui cores, tipografia, composição, linguagem e aplicações.'], ['Posso contratar só a identidade visual?', 'O escopo é definido conforme o momento da empresa, preservando o fundamento estratégico necessário.'], ['Vocês entregam arquivos editáveis?', 'A entrega é organizada com formatos adequados às aplicações previstas e orientações de uso.']],
    related: ['branding', 'criacao-de-sites', 'estrategia-de-marketing'],
  },
  {
    slug: 'branding',
    name: 'Branding',
    owner: 'Eudes',
    eyebrow: 'MARCA COMO DIREÇÃO',
    promise: 'Posicionamento e mensagem para construir percepção com consistência.',
    context: 'Branding define o lugar que a marca busca ocupar, a ideia que precisa sustentar e o modo como se expressa. É a camada estratégica que orienta decisões de identidade, comunicação e experiência.',
    deliverables: ['Diagnóstico e posicionamento', 'Proposta de valor e diferenciais', 'Arquitetura de mensagem', 'Direção verbal e pontos de contato'],
    process: [['Contexto', 'Lemos negócio, cultura, público e cenário competitivo.'], ['Posição', 'Escolhemos uma ideia central que seja relevante e sustentável.'], ['Linguagem', 'Traduzimos a posição em mensagens, tom e princípios.'], ['Coerência', 'Conectamos a estratégia às experiências da marca.']],
    faqs: [['Qual a diferença entre branding e identidade visual?', 'Branding organiza posicionamento e percepção; a identidade visual transforma parte dessa direção em um sistema reconhecível.'], ['Uma marca existente pode passar por branding?', 'Sim. O trabalho pode clarear, reposicionar ou alinhar uma marca sem necessariamente apagar sua história.'], ['O branding termina em um documento?', 'O documento registra decisões, mas o valor aparece quando elas orientam produto, comunicação e experiência.']],
    related: ['criacao-de-marca', 'estrategia-de-marketing', 'criacao-de-sites'],
  },
]

const cities = [
  {
    slug: 'itapipoca', name: 'Itapipoca', eyebrow: 'ESTRATÉGIA A PARTIR DO CONTEXTO',
    promise: 'Marketing digital em Itapipoca para negócios que querem organizar o próximo movimento.',
    context: 'Marcas de Itapipoca podem crescer sem imitar a comunicação de mercados distantes. A Oriz parte da realidade do negócio, da relação com o público e dos objetivos comerciais para conectar marca, presença digital e aquisição.',
    focus: 'Clareza para negócios que crescem conectando a cidade e a região.',
    faqs: [['A Oriz atende empresas de Itapipoca presencialmente?', 'O atendimento pode combinar conversas remotas e encontros definidos conforme o projeto, sem depender de uma rotina física fixa.'], ['Quais serviços estão disponíveis?', 'Estratégia, tráfego pago, sites, SEO, criação de marca e branding podem ser conectados conforme a prioridade.'], ['É possível começar por uma única frente?', 'Sim. O diagnóstico ajuda a escolher o ponto de partida sem transformar todas as possibilidades em obrigação.']],
  },
  {
    slug: 'fortaleza', name: 'Fortaleza', eyebrow: 'PRESENÇA EM UM MERCADO MAIS AMPLO',
    promise: 'Marketing digital em Fortaleza com estratégia para disputar atenção sem perder identidade.',
    context: 'Em um mercado com mais mensagens, canais e concorrência por atenção, consistência vale tanto quanto alcance. A Oriz estrutura posicionamento, experiência e distribuição para marcas que precisam ser reconhecidas pelo motivo certo.',
    focus: 'Estrutura para competir por atenção com uma mensagem própria.',
    faqs: [['A Oriz atende empresas de Fortaleza à distância?', 'Sim. O processo é organizado para decisões e entregas remotas, com encontros alinhados quando fizerem sentido.'], ['Vocês trabalham ações isoladas?', 'Podemos começar por uma necessidade específica, mantendo a conexão com o objetivo do negócio.'], ['Como é definido o escopo?', 'A primeira conversa identifica prioridade, maturidade e dependências antes da proposta.']],
  },
  {
    slug: 'trairi', name: 'Trairi', eyebrow: 'PRESENÇA QUE ACOMPANHA O RITMO',
    promise: 'Marketing digital em Trairi para comunicar valor em diferentes momentos de procura.',
    context: 'Negócios que recebem públicos em ritmos distintos precisam de uma presença que continue clara antes, durante e depois do contato. A Oriz organiza a marca e seus canais para manter coerência ao longo dessa jornada.',
    focus: 'Consistência para negócios que recebem públicos em momentos distintos.',
    faqs: [['A Oriz atende turismo e serviços em Trairi?', 'A estratégia é adaptada ao modelo de negócio, à jornada do público e aos momentos de demanda, sem pacote genérico por setor.'], ['É possível melhorar um site existente?', 'Sim. Primeiro avaliamos se a estrutura atual suporta os objetivos ou se uma reconstrução será mais eficiente.'], ['As campanhas podem variar ao longo do ano?', 'Sim. Planejamento e distribuição podem acompanhar mudanças reais de procura e prioridade.']],
  },
  {
    slug: 'amontada', name: 'Amontada', eyebrow: 'DESCOBERTA QUE VIRA RELAÇÃO',
    promise: 'Marketing digital em Amontada para transformar descoberta em uma presença duradoura.',
    context: 'Ser descoberto é apenas o início. A mensagem, o site e a experiência precisam sustentar o interesse e tornar o próximo passo simples. A Oriz conecta esses pontos para negócios que querem construir além de uma aparição pontual.',
    focus: 'Uma estrutura que transforma descoberta em relacionamento.',
    faqs: [['Posso contratar apenas criação de marca?', 'Sim. A identidade pode ser o ponto de partida, com espaço para conectar site, SEO ou mídia depois.'], ['A Oriz cria landing pages para campanhas?', 'Sim. A página é planejada junto à mensagem, à origem do tráfego e à ação esperada.'], ['Como funciona o atendimento regional?', 'Usamos um processo remoto claro e alinhamos encontros quando eles agregam ao projeto.']],
  },
  {
    slug: 'itapaje', name: 'Itapajé', eyebrow: 'CLAREZA PARA SER ESCOLHIDO',
    promise: 'Marketing digital em Itapajé para tornar a oferta mais clara e a presença mais consistente.',
    context: 'Quando o público não entende rapidamente o valor de uma empresa, cada canal perde eficiência. A Oriz trabalha posicionamento, comunicação e experiência para reduzir ruído e criar uma direção reconhecível.',
    focus: 'Organização digital para uma oferta mais fácil de compreender.',
    faqs: [['A estratégia serve para negócios locais?', 'Sim. O tamanho do mercado muda as escolhas, não a necessidade de clareza e consistência.'], ['Preciso refazer toda a marca?', 'Não necessariamente. O diagnóstico mostra o que pode ser preservado, refinado ou reconstruído.'], ['Vocês cuidam de SEO local?', 'Sim, com conteúdo e estrutura que representam a atuação real do negócio sem inventar presença física.']],
  },
  {
    slug: 'sobral', name: 'Sobral', eyebrow: 'ESTRUTURA PARA EXPANSÃO',
    promise: 'Marketing digital em Sobral para marcas que querem crescer com direção regional.',
    context: 'Expandir presença exige mais do que aumentar volume. A marca, o site, os canais e a leitura de dados precisam trabalhar com a mesma lógica. A Oriz constrói essa base para decisões mais coerentes ao longo do crescimento.',
    focus: 'Direção para marcas em expansão e conexão regional.',
    faqs: [['A Oriz atende empresas de Sobral remotamente?', 'Sim. Descoberta, reuniões, apresentações e validações podem acontecer de forma remota com um fluxo organizado.'], ['É possível unir branding e performance?', 'Sim. Posicionamento e distribuição cumprem papéis diferentes, mas ganham força quando compartilham a mesma direção.'], ['Por onde um projeto começa?', 'Por uma conversa sobre o estágio atual, os objetivos e o principal ponto de fricção.']],
  },
]

module.exports = { owners, services, cities }
